name: SCREAM!!!

on:
 schedule:
   # twice a day; 0400 and 1600 UTC
   - cron: '0 4/12 * * 1-5'

jobs:
  scream:
    name: SCREAM!!!
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: node src/main.js
        env:
          MASTODON_SERVER_URL: ${{ secrets.SERVER_URL }}
          MASTODON_API_TOKEN: ${{ secrets.API_TOKEN }}